export const ADD_TIMESHEET_TASK = "ADD_TIMESHEET_TASK";
export const CLEAR_TIMESHEET_TASK = "CLEAR_TIMESHEET_TASK";
export const SHOW_ALERT_MODAL = "SHOW_ALERT_MODAL";
export const CLEAR_ALERT_MODAL = "CELAR_ALERT_MODAL";
export const OPEN_ADD_EMPLOYEE_MODAL = "OPEN_ADD_EMPLOYEE_MODAL";
export const FORCE_RENDER = "FORCE_RENDER";
